#### Cleaning and doing Exploratory Datat Analysis for reddit_bookssuggestions dataset

In [1]:
# imports needed
import pandas as pd

In [2]:
# load the data
df = pd.read_csv("/Users/camila/ai201-project3-takemeter-starter-v2026/data/reddit_booksuggestions.csv")
df.head()

,title,score,id,url,comms_num,created,body
0,Any books about actually putting in the time a...,1,rktlhu,https://www.reddit.com/r/booksuggestions/comme...,0,1640024445,Anything could work;
1,"Does anybody know that book ""How to win Friend...",2,rkrbru,https://www.reddit.com/r/booksuggestions/comme...,3,1640018294,"If you don't, you need to know because it's pr..."
2,"Folk tales, myths and legends from all over th...",3,rkpi1e,https://www.reddit.com/r/booksuggestions/comme...,1,1640013305,"Hi, I'm looking for any books of folk tales, m..."
3,Books similar to Leaving Las Vegas?,1,rkol1h,https://www.reddit.com/r/booksuggestions/comme...,0,1640010731,Just finished this and really enjoyed the dark...
4,"Before I Go To Sleep, but not Before I Go To S...",0,rkol15,https://www.reddit.com/r/booksuggestions/comme...,1,1640010730,"Hi everyone,\n\nI'm looking for a recommendati..."

In [3]:
# convert created to datetime
df["created_utc"] = pd.to_datetime(df["created"], unit="s")
print(df["created_utc"].head())

0   2021-12-20 18:20:45
1   2021-12-20 16:38:14
2   2021-12-20 15:15:05
3   2021-12-20 14:32:11
4   2021-12-20 14:32:10
Name: created_utc, dtype: datetime64[ns]

In [4]:
# store the relevant data (all columns except created) into new dataframe
books_recs = df.drop(columns = ["created"]).copy()

In [5]:
# check average length of the body 
books_recs['body'].str.len().describe()


# dataset reduction section:

# cleaning duplicates, taking away leading or treading spaces and no data entries
books_recs = books_recs.drop_duplicates(subset="id")
books_recs = books_recs.drop_duplicates(subset=["body"])
books_recs["body"] = books_recs["body"].str.strip()
books_recs = books_recs[~books_recs["body"].isin(["", "[remonved]", "[deleted]"])]

# keep entries with considerable text 
books_recs = books_recs[books_recs["body"].str.len() >= 200]
# check posts left
print("Posts after cleaning:", len(books_recs))

# random sample of 200
books_recs = books_recs.sample(n=200, random_state=42)

Posts after cleaning: 2906

In [6]:
books_recs.head()

,title,score,id,url,comms_num,body,created_utc
232,Books for young adult(20s) just starting to re...,4,rdq8fu,https://www.reddit.com/r/booksuggestions/comme...,9,"My friend (F, early 20s) is interested in star...",2021-12-11 03:16:27
2392,Psychologists Seligman and Peterson developed ...,0,rgj5rz,https://www.reddit.com/r/booksuggestions/comme...,1,"In 2004, Seligman and Peterson published ""*Cha...",2021-12-14 22:32:00
1048,Comment,1,hp7ohem,NaN,0,[**The Naked and the Dead**](https://www.goodr...,2021-12-19 20:59:08
3681,Suggestions for exophonic books (written in En...,2,rpwyow,https://www.reddit.com/r/booksuggestions/comme...,8,I'm looking for books originally written in En...,2021-12-27 20:49:25
3710,Looking for thrillers/spy and military novels ...,3,rpldsp,https://www.reddit.com/r/booksuggestions/comme...,2,"Exposition dumps are fine, even helpful to mov...",2021-12-27 11:19:02

In [7]:
# 5. Save
books_recs.to_csv("labels.csv", index=False)

#### Rebalancing data after seeing label percentages in file - rebalance.py

```
book_centered      | 	118 (59.0%) 
template	   |    21 (10.5%)  
personal	   |    30 (15.0%)  
bare_ask	   |    31 (15.5%)  
```

label percentages after rebalance.py:

```
book_centered	95	47.5% 
template	44	22.0% 
personal	30	15.0% 
bare_ask	31	15.5% 

```